const brisbaneStreets = [ { label: `Adelaide Street`},
 { label: `Albert Street`},      
 { label: `Alice Street`},      
 { label: `Ann Street`},      
 { label: `Boomerang Street`},      
 { label: `Boundary Street`},      
 { label: `Burnett Lane`},      
 { label: `Charlotte Street`},      
 { label: `Clark Lane`},      
 { label: `College Road`},      
 { label: `Coronation Drive`},      
 { label: `Countess Street`},      
 { label: `Creek Street`},      
 { label: `Diddams Lane`},      
 { label: `Eagle Lane `},     
 { label: `Eagle Street`},      
 { label: `Eagle Terrace`},     
 { label: `Edison Lane`},      
 { label: `Edward Street`},      
 { label: `Elizabeth Street`},      
 { label: `Ely Lane`},      
 { label: `Esk Lane`},      
 { label: `Exford Street`},      
 { label: `Felix Street`},      
 { label: `Gardens Point Road`},     
 { label: `Garrick Street`},      
 { label: `George Street`},      
 { label: `Giffin Lane`},      
 { label: `Herschel Street`},      
 { label: `Howard Street`},      
 { label: `Hutton Lane`},      
 { label: `Isles Lane`},      
 { label: `Ivory Lane`},      
{ label: `Macrossan Street`},      
{ label: `Makerston Street`},      
{ label: `Margaret Street`},      
{ label: `Market Street`},      
{ label: `Mary Street`},      
{ label: `May Street`},      
{ label: `North Quay`},      
{ label: `Parkland Boulevard`},      
{ label: `Perry Lane`},      
{ label: `Quay Street`},      
{ label: `Queen Street`},      
{ label: `Queens Wharf Road`},      
{ label: `Raff Street`},     
{ label: `Rich Lane`},      
{ label: `Roma Street`},      
{ label: `Saul Street`},      
{ label: `Skew Street`},      
{ label: `Stephens Lane`},      
{ label: `Tank Street`},      
{ label: `Turbot Street`},      
{ label: `Upper Roma Street`},      
{ label: `Wharf Street`},      
{ label: `Wickham Terrace`},      
{ label: `William Street`}];

export default brisbaneStreets;